name: Test Runner

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: m d test
      run: ./m d test
